openapi: 3.0.0
info:
  title: text
  version: 1.0.0
components:
  schemas:
    DataResult:
      type: object
      properties:
        code: { type: integer, format: int64 }
        message: { type: string }
    TextResponse_allOf_data:
      type: object
      properties:
        Label:
          description: |
            Normal: 正常 Porn: 色情 Abuse: 谩骂 Ad: 广告 Custom: 自定义
          example: Normal
          enum: [Normal, Porn, Abuse, Ad, Custom]
          type: string
        Keywords:
          description: 该字段用户返回当前命中的多个关键词，此字段可能返回null，表示取不到有效值
          example: [傻逼, 草他妈]
          type: array
          items:
            type: string
            nullable: true
        FilteredText:
          description: 如果被检测文本命中了自定义屏蔽词词库中的屏蔽词，则会返回当前字段，并将命中的屏蔽词替换为星号(*)。
          example: 我****
          type: string
      required: [Label]
    TextResponse_allOf:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/TextResponse_allOf_data'
    TextResponse:
      allOf:
        - $ref: '#/components/schemas/DataResult'
        - $ref: '#/components/schemas/TextResponse_allOf'
