openapi: 3.0.0
info:
  title: Responses
  version: 1.0.0
paths: {}
components:
  schemas:
    BaseResult:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
    LoginResponseData:
      type: object
      properties:
        token:
          type: string
    HeartbeatResponseData:
      type: object
      properties:
        ts:
          type: integer
          format: int64
  responses:
    LoginResponse:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/BaseResult'
              - type: object
                properties:
                  data:
                    $ref: '#/components/schemas/LoginResponseData'
    HeartbeatResponse:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/BaseResult'
              - type: object
                properties:
                  data:
                    $ref: '#/components/schemas/HeartbeatResponseData'
