openapi: 3.0.0
info:
  title: AllOfTest
  version: 1.0.0
paths: {}
components:
  schemas:
    Base:
      type: object
      properties:
        id:
          type: integer
          format: int64
    DataA:
      type: object
      properties:
        a:
          type: string
    Combo:
      allOf:
        - $ref: '#/components/schemas/Base'
        - $ref: '#/components/schemas/DataA'
        - type: object
          properties:
            extra:
              type: string
    Holder:
      type: object
      properties:
        combo:
          $ref: '#/components/schemas/Combo'
        combos:
          type: array
          items:
            $ref: '#/components/schemas/Combo'
