openapi: 3.0.0
info:
  title: Sample
  version: 1.0.0
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required: [id, name]
    Status:
      type: string
      enum: [available, pending, sold]
