openapi: 3.0.0
info:
  title: Inline
  version: 1.0.0
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
        customer:
          type: object
          properties:
            name:
              type: string
            address:
              type: object
              properties:
                city:
                  type: string
                zip:
                  type: string
        items:
          type: array
          items:
            type: object
            properties:
              sku:
                type: string
              qty:
                type: integer
