syntax = "proto3";
package test.v1;
option go_package = "example.com/test;test";

message DataResult {
  int64 code = 1;
  string message = 2;
}

message ImageResponse {
  int64 code = 1;
  ImageResponse_allOf_data data = 2;
  string message = 3;
}

message ImageResponse_allOf_data {
  ImageResponse_allOf_data_Label label = 1; // Normal: 正常 Porn: 色情 Abuse: 谩骂 Ad: 广告 Custom: 自定义
}

enum ImageResponse_allOf_data_Label {
  IMAGERESPONSE_ALLOF_DATA_LABEL_UNSPECIFIED = 0;
  IMAGERESPONSE_ALLOF_DATA_LABEL_NORMAL = 1;
  IMAGERESPONSE_ALLOF_DATA_LABEL_PORN = 2;
  IMAGERESPONSE_ALLOF_DATA_LABEL_ABUSE = 3;
  IMAGERESPONSE_ALLOF_DATA_LABEL_AD = 4;
  IMAGERESPONSE_ALLOF_DATA_LABEL_CUSTOM = 5;
}

